export { default as About } from './about/About';
export { default as Contact } from './contact/Contact.jsx';
export { default as Experience } from './experience/Experience.jsx';
export { default as Footer } from './footer/Footer.jsx';
export { default as Header } from './header/Header.jsx';
export { default as Navbar } from './navbar/Navbar.jsx';
export { default as Portfolio } from './portfolio/Portfolio.jsx';
export { default as Services } from './services/Services.jsx';
export { default as Testimonial } from './testimonial/Testimonial.jsx';
